# Once this file is changed, you'll need to trigger a Puppet run on the
# k8s workers (or whatever is running ocfweb) for the config to propagate to ocfweb.
---

force_lab_closed: true

# please remember: the banner is for urgent announcements!
# consider adding something to the website normally if it's not urgent or you
# plan to leave it there for a while.
banner_visible: true

banner_html: |
  <div class="update-banner" id="banner">
    <h4 id="banner-header">Summer 2021 Lab Update</h4>
    <p>
      The lab is still closed & will likely remain closed until further notice. We expect the lab to reopen for the fall semester.
      <br /><br />
      OCF services - physical lab access aside - are expected to remain available throughout the closure, including webhosting and mail. Please 'Contact Us' for more details!
    </p>
  </div>
  <style>
    #banner-header, #banner-header-2 {
      font-size: 125%;
    }
    #banner {
      display: block;
      color: black;
      font-size: 100%;
      background-color: #e6b129;
    }
    #banner:hover {
      background-color: #e6b129;
    }
  </style>
